version: '3'
services:
  luta_phoenix:
    container_name: luta_phoenix
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: luta_dev
      PGPORT: 5432
      PGHOST: luta_db
    ports:
      - "4000:4000"
    depends_on:
      - luta_db
  luta_db:
    container_name: luta_db
    image: postgres:13.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
